config:
  send_anonymous_usage_stats: False

serie_a_dbt:
  target: dev
  outputs:
    dev:
      type: postgres
      threads: 1
      host: localhost
      port: 5432
      user: "dbt"
      pass: "password1234"
      dbname: "dbt_test"
      schema: "seriea"
